apiVersion: v1
kind: ResourceQuota
metadata:
  name: aayaansh-compute-resources
  namespace: saba
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
